### ISSUE TITLE
Doesn't work from CLI

### ISSUE THREAD

**Issue by vadi2** [jaywcjlove/html-to-markdown-cli#6]
```
$ npx @wcj/html-to-markdown-cli ./changelog.html
sh: 1: html-to-markdown: not found
```

**Comment by jaywcjlove** [comment]
@vadi2 I cannot reproduce your problem.

![image](https://user-images.githubusercontent.com/1680273/225554755-9a6444b1-b665-4dca-8be0-b5ef87e10e69.png)

<img width="787" alt="image" src="https://user-images.githubusercontent.com/1680273/225554924-d3d864ad-d89f-42c0-b0bc-ef2f279f4a03.png">

**Comment by vadi2** [comment]
Yep, my bad, it is fine.
